; usagio Windows installer (NSIS)
;
; Built by the "build-windows" job in .github/workflows/release.yml /
; rc-release.yml, right alongside the existing .zip distributable (this
; installer is an ADDITIONAL release asset, not a replacement -- power
; users who prefer a portable unzip-and-run keep that option).
;
; What it does:
;   - Installs usagio.exe to %ProgramFiles%\usagio\
;   - Appends %ProgramFiles%\usagio\ to the SYSTEM Path (idempotent --
;     checks for an existing entry before appending, so re-running the
;     installer for an upgrade doesn't grow Path with duplicates)
;   - Creates a Start Menu shortcut using usagio.ico (the same icon file
;     generate-ico.ps1 produces for the .zip distributable)
;   - Writes standard Add/Remove Programs (Apps & Features) registry keys
;     pointing at the generated uninstaller
;   - Runs `usagio install` at the end of installation, registering
;     autostart + launching the menu bar -- mirrors the Homebrew formula's
;     post_install block (see release.yml's tap-bump step) so "install
;     means install" on every platform
;   - Supports silent install: `usagio-setup.exe /S`
;
; Expects these files to already exist alongside this script (staged by
; the release workflow before invoking makensis):
;   usagio.exe   -- the release binary for x86_64-pc-windows-msvc
;   usagio.ico   -- generated by generate-ico.ps1
;
; Version is passed in via `makensis /DVERSION=x.y.z installer.nsi`.

!ifndef VERSION
  !define VERSION "0.0.0"
!endif

!define PRODUCT_NAME "usagio"
!define PRODUCT_PUBLISHER "Matthew Jackson"
!define PRODUCT_WEBSITE "https://usagio.dev"
!define UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define ENV_KEY 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment'

Name "${PRODUCT_NAME}"
OutFile "usagio-v${VERSION}-x86_64-pc-windows-msvc-setup.exe"
InstallDir "$PROGRAMFILES64\usagio"
InstallDirRegKey HKLM "${UNINST_KEY}" "InstallLocation"
RequestExecutionLevel admin
SetCompressor /SOLID lzma

!include "MUI2.nsh"
!include "WinMessages.nsh"
!include "LogicLib.nsh"

!define MUI_ABORTWARNING
!define MUI_ICON "usagio.ico"
!define MUI_UNICON "usagio.ico"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

VIProductVersion "${VERSION}.0"
VIAddVersionKey "ProductName" "${PRODUCT_NAME}"
VIAddVersionKey "ProductVersion" "${VERSION}"
VIAddVersionKey "CompanyName" "${PRODUCT_PUBLISHER}"
VIAddVersionKey "FileDescription" "${PRODUCT_NAME} installer"
VIAddVersionKey "FileVersion" "${VERSION}"

; --- Classic strstr()-style substring search, needed because NSIS has no
; built-in "does string A contain string B" instruction: a linear scan
; comparing a sliding window of len(needle) against the needle.
; Reproduced twice (install/uninstall contexts can't share a function)
; with plain, unique label names.
;
; Call convention: Push haystack, Push needle, Call StrStr, Pop $R0.
; $R0 = "" if not found, else the haystack's remainder starting at the
; first match (so the match's start offset is len(haystack) - len($R0)).
; Uses plain Pop-for-input / Push-for-output (no Exch) so the stack effect
; is simple to verify: 2 items consumed, 1 item produced.
Function StrStr
  Pop $R1 ; needle (pushed last, popped first)
  Pop $R2 ; haystack
  Push $R3
  Push $R4
  Push $R5
  StrLen $R3 $R1
  StrCpy $R4 0
  strstr_loop:
    StrCpy $R5 $R2 $R3 $R4
    StrCmp $R5 $R1 strstr_done
    StrCmp $R5 "" strstr_done
    IntOp $R4 $R4 + 1
    Goto strstr_loop
  strstr_done:
  StrCpy $R1 $R2 "" $R4
  Pop $R5
  Pop $R4
  Pop $R3
  Push $R1
FunctionEnd

Function un.StrStr
  Pop $R1
  Pop $R2
  Push $R3
  Push $R4
  Push $R5
  StrLen $R3 $R1
  StrCpy $R4 0
  un_strstr_loop:
    StrCpy $R5 $R2 $R3 $R4
    StrCmp $R5 $R1 un_strstr_done
    StrCmp $R5 "" un_strstr_done
    IntOp $R4 $R4 + 1
    Goto un_strstr_loop
  un_strstr_done:
  StrCpy $R1 $R2 "" $R4
  Pop $R5
  Pop $R4
  Pop $R3
  Push $R1
FunctionEnd

; --- Append $INSTDIR to the machine Path, skipping if already present.
Function AddToPath
  Pop $0 ; dir to add
  Push $1
  Push $2

  ReadRegStr $1 HKLM "${ENV_KEY}" "Path"

  Push $1
  Push $0
  Call StrStr
  Pop $2
  ${If} $2 == ""
    ${If} $1 == ""
      StrCpy $1 "$0"
    ${Else}
      StrCpy $1 "$1;$0"
    ${EndIf}
    WriteRegExpandStr HKLM "${ENV_KEY}" "Path" "$1"
    SendMessage ${HWND_BROADCAST} ${WM_SETTINGCHANGE} 0 "STR:Environment" /TIMEOUT=5000
  ${EndIf}

  Pop $2
  Pop $1
FunctionEnd

; --- Remove $INSTDIR from the machine Path (handles first/middle/last/
; only-entry position).
Function un.RemoveFromPath
  Pop $0 ; dir to remove
  Push $1
  Push $2
  Push $3
  Push $4

  ReadRegStr $1 HKLM "${ENV_KEY}" "Path"

  ; Case 1: "$0;" -- our dir followed by a separator (first or middle entry).
  Push $1
  Push "$0;"
  Call un.StrStr
  Pop $2
  ${If} $2 != ""
    StrLen $3 $1          ; total length of the current Path
    StrLen $4 $2          ; length of the remainder starting at the match
    IntOp $3 $3 - $4      ; offset where the match starts == length of the prefix
    StrCpy $4 $1 $3       ; $4 = prefix (everything before "$0;")
    StrLen $3 "$0;"       ; length of the needle itself
    StrCpy $2 $2 "" $3    ; $2 = remainder with the leading "$0;" stripped off
    StrCpy $1 "$4$2"
    Goto un_rmpath_case_done
  ${EndIf}

  ; Case 2: ";$0" -- our dir at the very end, preceded by a separator.
  Push $1
  Push ";$0"
  Call un.StrStr
  Pop $2
  ${If} $2 != ""
    StrLen $3 $1
    StrLen $4 $2
    IntOp $3 $3 - $4
    StrCpy $1 $1 $3       ; everything before the match; drop the match entirely
    Goto un_rmpath_case_done
  ${EndIf}

  ; Case 3: Path is exactly our dir (the only entry).
  ${If} $1 == $0
    StrCpy $1 ""
  ${EndIf}

  un_rmpath_case_done:
  WriteRegExpandStr HKLM "${ENV_KEY}" "Path" "$1"
  SendMessage ${HWND_BROADCAST} ${WM_SETTINGCHANGE} 0 "STR:Environment" /TIMEOUT=5000

  Pop $4
  Pop $3
  Pop $2
  Pop $1
FunctionEnd

Section "usagio" SEC_MAIN
  SetOutPath "$INSTDIR"
  File "usagio.exe"
  File "usagio.ico"

  ; Add/Remove Programs entry
  WriteRegStr HKLM "${UNINST_KEY}" "DisplayName" "usagio"
  WriteRegStr HKLM "${UNINST_KEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKLM "${UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  WriteRegStr HKLM "${UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEBSITE}"
  WriteRegStr HKLM "${UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "${UNINST_KEY}" "DisplayIcon" "$INSTDIR\usagio.ico"
  WriteRegStr HKLM "${UNINST_KEY}" "UninstallString" '"$INSTDIR\Uninstall.exe"'
  WriteRegStr HKLM "${UNINST_KEY}" "QuietUninstallString" '"$INSTDIR\Uninstall.exe" /S'
  WriteRegDWORD HKLM "${UNINST_KEY}" "NoModify" 1
  WriteRegDWORD HKLM "${UNINST_KEY}" "NoRepair" 1
  WriteUninstaller "$INSTDIR\Uninstall.exe"

  ; Start Menu shortcut, icon from the bundled .ico (usagio.exe itself has
  ; no icon resource embedded at compile time -- same rationale as
  ; Create-Shortcut.ps1 for the .zip distributable).
  CreateDirectory "$SMPROGRAMS\usagio"
  CreateShortCut "$SMPROGRAMS\usagio\usagio.lnk" "$INSTDIR\usagio.exe" "" "$INSTDIR\usagio.ico"
  CreateShortCut "$SMPROGRAMS\usagio\Uninstall usagio.lnk" "$INSTDIR\Uninstall.exe"

  ; System PATH
  Push "$INSTDIR"
  Call AddToPath

  ; Register the menu bar / autostart, same as Homebrew's post_install.
  ; Runs even under /S silent install so unattended installs end up fully
  ; set up, matching "install means install" for every platform.
  DetailPrint "Running usagio install..."
  nsExec::ExecToLog '"$INSTDIR\usagio.exe" install'
  Pop $0
  ${If} $0 != 0
    DetailPrint "usagio install exited with code $0 -- you can run it manually later from $INSTDIR\usagio.exe"
  ${EndIf}
SectionEnd

Section "Uninstall"
  ; Best-effort: stop the menu bar / remove autostart before deleting
  ; files, mirroring `usagio uninstall` being the documented way to undo
  ; what `usagio install` (or the Homebrew post_install) set up.
  DetailPrint "Running usagio uninstall..."
  nsExec::ExecToLog '"$INSTDIR\usagio.exe" uninstall'
  Pop $0

  Push "$INSTDIR"
  Call un.RemoveFromPath

  Delete "$SMPROGRAMS\usagio\usagio.lnk"
  Delete "$SMPROGRAMS\usagio\Uninstall usagio.lnk"
  RMDir "$SMPROGRAMS\usagio"

  Delete "$INSTDIR\usagio.exe"
  Delete "$INSTDIR\usagio.ico"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir "$INSTDIR"

  DeleteRegKey HKLM "${UNINST_KEY}"
SectionEnd
